Repository who-wrote-that/cli, pull requests merged in 2019-11, with the labels that each got.

#1 find method by line or method
  .gitignore
  package.json
  src/@types/tree-sitter-java/index.d.ts
  src/index.ts
  src/util.ts
  test_files/Test.java
  yarn.lock
Labels: enhancement

#2 Feature/git show
  package.json
  src/git.ts
  src/index.ts
  src/parse.ts
  test_files/Test.java
  yarn.lock
Labels: enhancement

#3 git diff and codeowners
  diff-lines
  package.json
  src/codeowners.ts
  src/git.ts
  src/index.ts
  src/parse.ts
  yarn.lock
Labels: enhancement

#16 split author into name and email
  src/git.ts
Labels: enhancement

#17 ci
  .eslintrc.js
  .github/workflows/ci.yml
  .github/workflows/release.yml
  README.md
  package.json
  src/codeowners.ts
  src/git.ts
  src/index.ts
  src/parse.ts
  src/util.ts
Labels: enhancement

#24 Display help when invoked without arguments
  src/index.ts
Labels: enhancement

#27 Code owners not unique after change of Author type
  src/codeowners.ts
Labels: bug

#35 Class declarations parsed as empty string
  src/languages/java.ts
Labels: bug

#34 Remove owners with score 0 from result
  src/codeowners.ts
Labels: bug

#37 added multi language support
  src/codeowners.ts
  src/parse.ts
Labels: enhancement

#39 Squish scores
  src/codeowners.ts
  src/util.ts
Labels: enhancement

#38 Format output
  src/index.ts
Labels: enhancement

#41 added js support
  package.json
  src/@types/tree-sitter-javascript/index.d.ts
  src/@types/tree-sitter-typescript/index.d.ts
  src/languages/javascript.ts
  src/languages/typescript.ts
  src/parse.ts
  yarn.lock
Labels: enhancement

#45 added golang support
  package.json
  src/@types/tree-sitter-go/index.d.ts
  src/index.ts
  src/languages/go.ts
  src/parse.ts
  yarn.lock
Labels: enhancement

#47 option for json output
  src/index.ts
Labels: enhancement

#46 added python support
  package.json
  src/@types/tree-sitter-python/index.d.ts
  src/languages/python.ts
  src/parse.ts
  yarn.lock
Labels: enhancement

#43 Weigh score based on recency of commits
  src/codeowners.ts
  src/index.ts
Labels: enhancement

#53 colored output
  package.json
  src/index.ts
  yarn.lock
Labels: enhancement

#54 Command to lookup codeowners of a specific definition
  src/codeowners.ts
  src/index.ts
  src/parse.ts
Labels: enhancement

#55 Fix Java class name extract
  src/languages/java.ts
Labels: bug

#72 increased stdout buffer size from 200kb to 3mb
  src/git.ts
Labels: bug

#75 Update readme
  README.md
Labels: documentation

#79 [#78] Release workflow: Compile to lib folder before publishing
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: bug

#83 Fix readme
  README.md
Labels: documentation

#81 [#68] Calculate code ownership as relative to line length of code block
  src/WhoWroteThat.ts
  src/index.ts
Labels: enhancement

#84 Fix decl not working
  src/Parser.ts
Labels: bug

#80 use node.children to extract function name
  src/languages/Go.ts
Labels: bug
