Repository who-wrote-that/cli, pull requests merged in 2020-01, with the labels that each got.

#120 [#36] Use field name `name` provided by tree sitter
  .eslintrc.js
  .github/workflows/ci.yml
  .gitignore
  .tool-versions
  package.json
  src/index.ts
  src/languages/Go.ts
  src/languages/Java.ts
  src/languages/JavaScript.ts
  src/languages/Python.ts
  src/languages/util.ts
Labels: enhancement, language

#123 add typescript support
  README.md
  package.json
  src/@types/tree-sitter-typescript/index.d.ts
  src/languages/TSX.ts
  src/languages/TypeScript.ts
  src/languages/index.ts
  yarn.lock
Labels: enhancement

#122 fix bug in `findDeclarationByName`
  src/Parser.ts
Labels: bug

#126 use git format to only list commit hashes
  src/Git.ts
Labels: bug

#125 analyze entire files
  README.md
  src/Parser.ts
  src/WhoWroteThat.ts
  src/index.ts
  src/languages/Go.ts
Labels: enhancement
